/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phex_utils_WindowsShellExecute */

#ifndef _Included_phex_utils_WindowsShellExecute
#define _Included_phex_utils_WindowsShellExecute
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: isNativeLibLoaded */
/*
 * Class:     phex_utils_WindowsShellExecute
 * Method:    shellExecute
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_phex_utils_WindowsShellExecute_shellExecute
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif