/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phex_gui_common_DesktopIndicator */

#ifndef _Included_phex_gui_common_DesktopIndicator
#define _Included_phex_gui_common_DesktopIndicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     phex_gui_common_DesktopIndicator
 * Method:    nativeDisable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phex_gui_common_DesktopIndicator_nativeDisable
  (JNIEnv *, jobject);

/*
 * Class:     phex_gui_common_DesktopIndicator
 * Method:    nativeEnable
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_phex_gui_common_DesktopIndicator_nativeEnable
  (JNIEnv *, jobject, jint, jstring);
  
/*
 * Class:     phex_gui_common_DesktopIndicator
 * Method:    setNativeMenuText
 * Signature: (ILjava/lang/String;)V, (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_phex_gui_common_DesktopIndicator_setNativeMenuText
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     phex_gui_common_DesktopIndicator
 * Method:    nativeFreeImage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_phex_gui_common_DesktopIndicator_nativeFreeImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     phex_gui_common_DesktopIndicator
 * Method:    nativeLoadImage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_phex_gui_common_DesktopIndicator_nativeLoadImage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     phex_gui_common_DesktopIndicator
 * Method:    nativeLoadImageIDFromResource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_phex_gui_common_DesktopIndicator_nativeLoadImageIDFromResource
  (JNIEnv *, jclass, jint);
  
/*
 * Class:     phex_gui_common_DesktopIndicator
 * Method:    nativeLoadImageIDFromResource
 * Signature: Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_phex_gui_common_DesktopIndicator_nativeLoadImageIDStrFromResource
  (JNIEnv *, jclass, jstring);


/*
 * Class:     phex_gui_common_DesktopIndicator
 * Method:    nativeHide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phex_gui_common_DesktopIndicator_nativeHide
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
